### ISSUE TITLE
运行无法反应

### ISSUE THREAD

**Issue by liubangjain** [Mrs4s/six-cli#10]
ubuntu18.04运行最新的six，运行后没有任何反应，没有任何提示。

**Comment by hagemouse** [comment]
一样的问题，很长时间了。

**Comment by TK4E** [comment]
Ubuntu 18.04.5

sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
apt-get dist-upgrade
sudo apt install golang-go
git clone https://github.com/Mrs4s/six-cli.git
cd six-cli
go get github.com/Mrs4s/six-cli
go build
./six-cli

**Comment by Paull** [comment]
同，运行无反应，errcode 127。
```bash
$ ./six-cli 
$ echo $?
127
```
从release下载的six-cli_V0.0.6-alpha_linux_amd64.tar.gz，我的系统是：
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
```

**Comment by hagemouse** [comment]
root@vps23:~/six-cli# go get github.com/Mrs4s/six-cli
# github.com/Mrs4s/power-liner
../go/src/github.com/Mrs4s/power-liner/shell.go:144:32: undefined: strings.ReplaceAll
# github.com/Mrs4s/go-http-downloader
../go/src/github.com/Mrs4s/go-http-downloader/downloader.go:35:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
# github.com/Mrs4s/go-six-cloud-upload-sdk
../go/src/github.com/Mrs4s/go-six-cloud-upload-sdk/uploader.go:32:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
root@vps23:~/six-cli# go build
# github.com/Mrs4s/power-liner
../go/src/github.com/Mrs4s/power-liner/shell.go:144:32: undefined: strings.ReplaceAll
# github.com/Mrs4s/go-http-downloader
../go/src/github.com/Mrs4s/go-http-downloader/downloader.go:35:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
# github.com/Mrs4s/go-six-cloud-upload-sdk
../go/src/github.com/Mrs4s/go-six-cloud-upload-sdk/uploader.go:32:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

**Comment by s912a42** [comment]
> root@vps23:~/six-cli# go get github.com/Mrs4s/six-cli
> 
> # github.com/Mrs4s/power-liner
> ../go/src/github.com/Mrs4s/power-liner/shell.go:144:32: undefined: strings.ReplaceAll
> 
> # github.com/Mrs4s/go-http-downloader
> ../go/src/github.com/Mrs4s/go-http-downloader/downloader.go:35:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
> 
> # github.com/Mrs4s/go-six-cloud-upload-sdk
> ../go/src/github.com/Mrs4s/go-six-cloud-upload-sdk/uploader.go:32:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
> root@vps23:~/six-cli# go build
> 
> # github.com/Mrs4s/power-liner
> ../go/src/github.com/Mrs4s/power-liner/shell.go:144:32: undefined: strings.ReplaceAll
> 
> # github.com/Mrs4s/go-http-downloader
> ../go/src/github.com/Mrs4s/go-http-downloader/downloader.go:35:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
> 
> # github.com/Mrs4s/go-six-cloud-upload-sdk
> ../go/src/github.com/Mrs4s/go-six-cloud-upload-sdk/uploader.go:32:20: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

I think this is because you are using an old version of golang that causes this problem.
You should refer to this [https://golang.org/doc/go1.12](https://golang.org/doc/go1.12)(strings.ReplaceAll available after this version), and update your golang version.

**Comment by hagemouse** [comment]
> 
> I think this is because you are using an old version of golang that causes this problem.
> You should refer to this https://golang.org/doc/go1.12(strings.ReplaceAll available after this version), and update your golang.


Yes, now it works.
Thank you.
