### ISSUE TITLE
下载中断，response status unsuccessful: 403

### ISSUE THREAD

**Issue by targaryener** [Mrs4s/six-cli#11]
下载几秒后提示response status unsuccessful: 403，任务终止然后一直卡住

**Comment by Mrs4s** [comment]
请问一下运行前修改过配置文件没

**Comment by targaryener** [comment]
> 请问一下运行前修改过配置文件没

没有修改过配置文件的，Ubuntu 18.04.4 LTS (GNU/Linux 5.0.0-1034-gcp x86_64)，谷歌云

**Comment by Mrs4s** [comment]
好的，这是我们服务端的bug 现在正在排查中

**Comment by targaryener** [comment]
> 好的，这是我们服务端的bug 现在正在排查中

辛苦大佬了

**Comment by Mrs4s** [comment]
请尝试下最新的Build, 应该解决了这个问题
