### ISSUE TITLE
单个文件夹，最多能够添加或者显示500个文件

### ISSUE THREAD

**Issue by Syincheng** [Mrs4s/six-cli#13]
不管是CLI，还是generic客户端

**Comment by zhangweiii** [comment]
找到了一个源码`limit:500`
路径：six_cloud -> user.go 37行
基于`0eba4dcf0b9939019992a2e8b86b3f4389ec39af`这个提交

**Comment by Syincheng** [comment]
> 找到了一个源码`limit:500`
> 路径：six_cloud -> user.go 37行
> 基于`0eba4dcf0b9939019992a2e8b86b3f4389ec39af`这个提交

thanks!
