### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by yuritry** [Mrs4s/six-cli#5]
不知道什么原因。
老大什么时候更新一版？

**Comment by loeveo** [comment]
SSNI-542.mp4 2.69 GiB / 6.31 GiB [=========>------------]  42.59% 7.36 MiB/s 08m21spanic: runtime error: index out of range [0] with length 0

goroutine 1153 [running]:
github.com/Mrs4s/go-http-downloader.(*DownloaderClient).BeginDownload.func1.1(0xc000488ae0, 0xc0001345a0)
        /Users/sijiang/go/pkg/mod/github.com/!mrs4s/go-http-downloader@v0.0.0-20191014103207-7f76db391012/downloader.go:84 +0x1ae
created by github.com/Mrs4s/go-http-downloader.(*DownloaderClient).BeginDownload.func1
        /Users/sijiang/go/pkg/mod/github.com/!mrs4s/go-http-downloader@v0.0.0-20191014103207-7f76db391012/downloader.go:64 +0x246
